name: Build docker images
on:
    push:
        # Publish `master` as Docker `latest` image.
        branches:
            - master
            - scoped-docker-image-test

        # Publish `v1.2.3` tags as releases.
        tags:
            - '*'

jobs:
    publish_images:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                php-version: ['7.4', '8.0']
        steps:
            - uses: actions/checkout@v2

            - name: Log into container registries
              run: |
                  echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
                  echo ${{ secrets.DOCKER_SECRET }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            - name: Build images
              run: |
                  # Strip git ref prefix from version
                  VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

                  # Strip "v" prefix from tag name
                  [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

                  # Use Docker `latest` tag convention
                  [ "$VERSION" == "master" ] && VERSION=latest

                  docker buildx create --name builder-php${{ matrix.php-version }} --use
                  docker buildx build \
                        --cache-from=ghcr.io/$GITHUB_REPOSITORY:build-cache-php${{ matrix.php-version }} \
                        --cache-to=type=registry,ref=ghcr.io/$GITHUB_REPOSITORY:build-cache-php${{ matrix.php-version }},mode=max,push=true \
                        --target rector \
                        --push \
                        --tag $GITHUB_REPOSITORY:$VERSION-php${{ matrix.php-version }} \
                        --tag $GITHUB_REPOSITORY:latest-php${{ matrix.php-version }} \
                        --build-arg PHP_VERSION=${{ matrix.php-version }} .
